v = input("Digite uma frase: ")
f = (v.lower()).strip()
print("A letra 'a' aparece {} vezes na frase.".format(f.count("a")))
print("A primeira letra 'a' apareceu na posição {}".format(f.find('a')+1 ))
print("A última letra 'a' apareceu na posição {}".format(f.rfind('a')+1))